### ISSUE TITLE
How to present UIActivityViewController on one of the root pages

### ISSUE THREAD

**Issue by rawmean** [MarioIannotta/MIPivotPageController#5]
I get the "Presenting view controllers on detached view controllers is discouraged" when I try to present a UIActivityViewController on a root page.  
I think the root page needs to present the UIActivityViewController on the rootPageController and not on itself.
How to get access to the rootPageController from one of the root pages?
Is there a better way to do this?

Thanks much for the repo.

**Comment by MarioIannotta** [comment]
Hi, you are absolutely right; in my case the pivotPageController is the root of my application so I can access it through `UIApplication.shared.delegate?.window??.rootViewController`

I hope this works for you but I'll think about a less tricky way for achieve this.

**Comment by rawmean** [comment]
I ended up passing the root page controller to the MIPivotPage explicitly and now it works fine and the error message is gone
