### ISSUE TITLE
Presenting a view controller modally on top of MIPivotPage

### ISSUE THREAD

**Issue by rawmean** [MarioIannotta/MIPivotPageController#6]
When I try to present another view controller (MFMailViewController) on one of the MIPivotPages, upon dismissing the page controller, the MIPivotPage is not rendered correctly (it's all white).  If I swipe left and then right to come back to the page, it gets rendered again correctly.

Do you know how this can be fixed?  Thanks.

**Comment by Alex293** [comment]
You can still use the presentation style to overfullscreen in the modal segue into storyboard or as property in the vc but this is not really a fix

**Comment by rawmean** [comment]
Thanks.  That works for now.  It's the same solution that I used for the other issue that I opened (related to presenting the UIActivityController).
